[project]
name = "cph"
version = "0.1.2"
description = "A simple helper script for competitive programming"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["typer>=0.20.0"]

[project.scripts]
cph = "cph.__main__:app"
